[project]
name = "lttrpy"
version = "2024.2"

authors = [{name = "Said Sattarov", email = "said.sattarov@gmail.com"}]
maintainers = [{name = "Said Sattarov", email = "said.sattarov@gmail.com"}]

description = "A script to compare several users' watched films on Letterboxd, with ratings and likes"
readme = "README.md"

requires-python = ">=3.10"
dependencies = [
    "aiohttp",
    'lxml',
]

keywords = ["letterboxd", "films", "movies"]
classifiers = ["Development Status :: 3 - Alpha",
			   "License :: OSI Approved :: MIT License",
]			   

[project.urls]
Repository = "https://github.com/JinEnMok/lttrpy"

[project.optional-dependencies]
fast = ["uvloop; sys_platform=='linux' or sys_platform=='darwin'"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
lttrpy = "lttrpy:main"
